sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t redavtovo/armhf-socat:build .
# test image
- docker run redavtovo/armhf-socat:build version
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep download Dockerfile | sed 's,.*/download/,,' | sed 's,/.*$,,')
    docker tag redavtovo/armhf-socat:build redavtovo/armhf-socat:$TAG
    docker push redavtovo/armhf-socat:$TAG
    docker tag redavtovo/armhf-socat:build redavtovo/armhf-socat:latest
    docker push redavtovo/armhf-socat:latest
  fi